spring:
  datasource:
    url: jdbc:postgresql:kumys
    username: kumys
    password: kumys
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 50


server:
  servlet:
    context-path: /api