spring:
  datasource:
    url: jdbc:postgresql:kymyz
    username: kymyz
    password: kymyz
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 50


server:
  servlet:
    context-path: /api